import {
  Home,
  Users,
  Folder,
  Bell,
  Search,
  Plus,
  Filter,
  Download,
  Flag,
  Cake,
  Coffee,
  CalendarCheck,
  Calendar,
  Sparkles,
  Target,
  Briefcase,
  Mail,
  Telephone,
  MapPin,
  Building,
  CheckCircle,
  Check,
  DotsVertical,
  X,
  ArrowUpRight,
  ChevronRight,
  Edit,
  Message,
  Star,
  ClockCircle,
  Cog,
  User,
  Globe,
  File,
  Upload,
  Logout,
  Key,
  Link,
  Google,
  Linkedin,
} from "@mynaui/icons-react";

export const Icons = {
  home: Home,
  users: Users,
  folder: Folder,
  bell: Bell,
  search: Search,
  plus: Plus,
  filter: Filter,
  download: Download,
  flag: Flag,
  cake: Cake,
  coffee: Coffee,
  calendarCheck: CalendarCheck,
  calendar: Calendar,
  sparkles: Sparkles,
  target: Target,
  briefcase: Briefcase,
  mail: Mail,
  phone: Telephone,
  pin: MapPin,
  building: Building,
  checkCircle: CheckCircle,
  check: Check,
  dots: DotsVertical,
  x: X,
  arrowUpRight: ArrowUpRight,
  chevronRight: ChevronRight,
  edit: Edit,
  message: Message,
  star: Star,
  clock: ClockCircle,
  settings: Cog,
  user: User,
  globe: Globe,
  file: File,
  upload: Upload,
  logout: Logout,
  key: Key,
  link: Link,
  google: Google,
  linkedin: Linkedin,
} as const;

export type IconKey = keyof typeof Icons;
